spring.application.name=HospitalManagementSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_management_system_db
spring.datasource.username=postgres
spring.datasource.password=Shruti@1

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#Configuration for jwt
jwt.secret=sfa2sfdf349vsdfqewfnddf0d239fdsafv45hrat23fhrsfweqwe32wetgbtruj67tytyb
jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#FOR SQL RUN
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true